name: Build-Test-BatAxeKernel
run-name: 'CI: Build ${{ github.event.inputs.version }} for device ${{ github.event.inputs.devices }} With Clang ${{ github.event.inputs.llvm }}'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Kernel Version'
        required: true
        default: ''
      branch:
        description: 'BatAxeKernel Branch'
        required: true
        default: ''
      ksun:
        description: 'Install KernelSU-Next ?'
        required: true
        default: 'y'
      llvm:
        description: 'Clang (12-18) (19-21:Potential bootloop on A12) or Neutron (10032024) Version'
        required: true
        default: '10032024'
        type: choice
        options:
          - '12'
          - '13'
          - '14'
          - '15'
          - '16'
          - '17'
          - '18'
          - '19'
          - '20'
          - '21'
          - '10032024'
      devices:
        description: 'Devices'
        required: true
        default: '["d1"]'
        type: choice
        options: 
          - ["d1"]
          - ["d1xks"]
          - ["d2s"]
          - ["d2x"]
          - ["beyond0lte"]
          - ["beyond1lte"]
          - ["beyond2lte"]
          - ["beyondx"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        device: ${{ fromJSON(github.event.inputs.devices) }}

    steps:
      - name: 📀 Checkout Kernel Repository
        uses: actions/checkout@v4
        with:
          repository: papaL3xa/BatAxeKernel
          ref: ${{ github.event.inputs.branch }}  # atau branch yang sesuai
          token: ${{ secrets.GITHUB_TOKEN }}
          path: kernel-source

      - name: ⏰ Set Time Zone
        run: |
          sudo timedatectl set-timezone Asia/Jakarta 

      - name: 🪡 Setup Build Environment
        run: |
          sudo apt update && sudo apt upgrade -y && sudo apt install --no-install-recommends -y build-essential gcc-aarch64-linux-gnu clang lld llvm
          
      - name: 💼 Set Environment Variable
        run: |
          cd kernel-source
          SHA=$(git rev-parse --short ${{ github.sha }})
          echo BUILD_DATE=$(date +'%Y%m%d') >> $GITHUB_ENV
          echo BUILD_KERNEL_VERSION=CI-${{ github.event.inputs.version }}-$SHA >> $GITHUB_ENV

      - name: ⚙️ Setting permission for build.sh
        run: |
          cd kernel-source
          chmod +x build.sh

      - name: 🏇🏻 Building Kernel
        run: |
          cd kernel-source
          bash build.sh -m ${{ matrix.device }} -v ${{ env.BUILD_KERNEL_VERSION }} -k ${{ github.event.inputs.ksun }} -l ${{ github.event.inputs.llvm }} -r n

      - name: 🧩 Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: "BatAxeKernel-${{ env.BUILD_KERNEL_VERSION }}-${{ env.BUILD_DATE }}-${{ matrix.device }}-Clang${{ github.event.inputs.llvm }}"
          path: "kernel-source/build/out/${{ matrix.device }}/zip/*"
          if-no-files-found: error